holidayextras/holidayextras.github.com

_includes/head.html
- We put in a request to twitter to have our twitter name changed from @HXHungryGeek to @TheHungryGeek
- The username was taken, but wasn't being used by the owner
- Twitter don't freely remove non-active users from twitter and change usernames but we were luckily very successful.
- I use twitter cards on The Hungry Geek to promote our blog posts and tweets - (https://cards-dev.twitter.com/validator)
- This PR changes the twitter username.
=> Adjusting twitter card data for new twitter account

README.md, _posts/2015-02-16-developing-the-right-culture.md
A blog post originally created on Medium which we now have permission to move onto Hungry Geek
**PR on behalf of @notABluesSinger**
=> "Developing the right culture"  by Rob Johnson

_posts/2015-02-24-making-stuff-happen.md
Too many todo's... here's how you make stuff happen
- Download the branch, run ```jekyll serve```
- Visit http://localhost:4000/workflow/2015/02/24/making-stuff-happen/
- [/] I've updated documentation with any changes to procedures.
- [/] I've tested this on mobile Android, Safari, Chrome for any visual changes.
I was unable to get Jekyll working, too little time, will fix later, so if this could be reviewed with the reviewer checking for visuals that would be awesome, thanks.
=> Added making stuff happen post

projects/esq.md, projects/index.html
Creates a project page for ESQ 
- An easy way to build elasticsearch queries without having to writing lots and lots of code
Adds that page to the project page on Hungry Geek.
- Run ```gem install jekyll```
- Run ```bundle install```
- Run ```jekyll serve``` to load up hungry geek locally.
- Visit http://127.0.0.1:4000/projects/ you should see a link to ESQ
- Visit http://127.0.0.1:4000/projects/esq/
=> Adding ESQ to our open source projects

_posts/2015-03-02-build-sites-dynamically-with-grunt.md
Build sites dynamically with grunt
How to post on building multiple sites with Grunt.
=> Build sites dynamically with grunt

_includes/styles.html
- Adds prefixing for old mobile phones like iPhone :trollface: 
- Also adds prefixing for opera, ie and firefox
- Run `jekyll serve --safe` this should boot up the blog locally
- Visit your IP address (localhost) on your phone (:4000/)
- ENSURE The team photos don't look like this
=> Iphone pain

_posts/2015-03-09-how-we-do-r&d-time-at-holiday-extras.md
How we do R&D time at Holiday Extras
An insight into how we do Project Lounge at Holiday Extras
=> How we do project lounge

_data/members.yml, _posts/2015-03-13-a-fresh-look-at-agile.md
A Fresh look at Agile
Briefly summarises the approach we take to agile. What makes the process work. What makes it better.
=> new post - A fresh look at Agile

_posts/2015-03-18-5-tips-for-a-smoother-code-review-process.md
5 tips for a smoother code review process
Title is fairly self explanatory, details some of the customisations we've made to our code review process for efficiency.
Please don't merge this at the moment, the links to the culture repo are broken because it's private. I'm going to chat to Rog about opening this up as there's no reason for it not to be public right now.
=> 5 tips for a smoother code review process

_data/members.yml, _includes/head.html, index.html, projects/index.html, team/index.html
- Change the meta description for each blog post to mention a snippet of information about the post itself
- Add Carolines MD5 Gravatar
- Removed "by Holiday Extras" and "The Tech Team at Holiday Extras" from the header on all pages.
- Run `jekyll serve --safe` this should boot up the blog locally
- Visit your IP address (localhost) on your phone (:4000/)
- Check the Meta Description and a few posts and default pages to ensure it makes sense
- Ensure all pictures of the team and now displayed
=> HX tech team

_includes/styles.html, _posts/2015-04-02-thinking-about-mobile.md
Thinking about mobile
A short post and video about our the Holiday Extras mobiletastic week.
As this post includes a video, i have added some styling to enable the youtube video to be responsive.
=> Thinking about mobile - A short post and video about our the Holiday Extras mobiletastic week.

_data/members.yml, _posts/2015-04-02-learning-the-basics-of-expressjs.md, _posts/2015-04-20-learning-the-basics-of-expressjs.md
Learning the Basics of ExpressJS
A tutorial which talks about some of the basic points of ExpressJS.
=> Blog Post - Learning the Basics of ExpressJS

_config.yml, _includes/styles.html, _layouts/post.html, index.html
- Increases the font size of the whole website.
- Add profile pictures to the homepage
- Truncates post summary to 50 words
- Increases posts per page to 10 (pagination)
- Run `jekyll serve`
- Visit `http://localhost:4000`
- Text should be bigger
- Profile pictures should appear next to each summary
- Posts are truncated to 50 words
- There are now 10 posts per page.
=> Increase font-size, pagination and visibility

_data/members.yml, _posts/2012-03-16-ssl-san-termination-in-the-amazon-cloud-with-elbs.md, _posts/2012-04-20-selenium-conference-day-1.md, _posts/2012-04-20-selenium-conference-day-2.md, _posts/2012-07-20-customise-your-prompt-with-git-information.md, _posts/2014-01-20-getting-performance-cordova-based-application.md, team/index.html
Having looked at Google Webmaster tools we have a lot of broken links
- This fixes a lot of the simple broken links on blog posts
- This adds in Dan Jenkins to the authors but lists him as no longer HX
- Run `jekyll serve`
- Visit `http://localhost:4000`
- Check out the individual changes in the code and ensure that the links now work properly
- Make sure Jan Jenkins has a picture but doesn't appear on the team page
=> Fixing broken links

404.html, 404.md, _includes/styles.html
Finally adds a 404 page to The Hungry Geek blog.
Bit quirky, i hope you like :laughing: 
- Run `jekyll serve`
- Visit `http://localhost:4000/thispageisnothere`
=> Adding a 404 page

_posts/2015-08-17-tab-complete-a-different-directory.md
Tab completing bash functions for a speedy workflow
Bash aliases & functions are awesome for ~~laziness~~productivity. My bash skills are fairly amateur but I like to have a dabble when I get the time to try & make my life easier. 
Looking for some feedback on this, be honest!
1. Can it be improved?
2. Is it actually useful/interesting?
=> Tab completing bash functions for a speedy workflow

_data/members.yml, _data/speaking.yml, profiles/liz-pope/index.md
**What's changed**
I've added my speaker profile and the London Web Meet up to the speaking calendar page. All that should have changed is extra content added.
**To Test**
Check I've not made any typos....
I've run the blog locally to make sure it all looks ok, but someone else should do that too
=> Adding my speaker profile and meet up date

_data/speaking.yml, profiles/matt-obee/index.md
Content changes so nothing should have broken, in theory. Typos are possible however.
=> Created a profile for myself and added my talk to the list.

_posts/2015-10-05-10-myths-about-software-testing.md
10 Myths about Software Testing
Following on loosely from my last post, this busts 10 of the most common myths in software testing.
=> First draft of "10 Myths about Software Testing"

_posts/2015-11-06--isn-t-that-your-job.md
=> Isn't that YOUR job?

_posts/2015-11-06--isn-t-that-your-job.md, _posts/2015-11-11-isnt-that-your-job.md
Reverts & fixes holidayextras/holidayextras.github.com#64
=> Revert "Revert "Isn't that YOUR job?""

_data/members.yml
I missed adding my profile + gravatar to members
=> Duncan Profile and gravatar

_posts/2015-11-18-clever-git.md
=> Missed typos

_jobs/ui-designer.md
We are getting a lot or research UXers applying for the jobs we are advertising, so to get the kinda of people we want (more design focussed) we are changing our job ad to ask for a *User Interface designer*
None
run `jekyll serve` then visit 
---
**Review 1**
**Review 2** \*
By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
=> Changing UX designer to UI designer

_jobs/full-stack-data-engineer.md
=> Add FS Data Engineer Job

_posts/2016-05-18-the-group-formerly-known-as-pos.md, _posts/2016-05-31-the-group-formerly-known-as-pos.md
The post has already been reviewed and merged, this PR will publish it on the HG site. **The date will need to be changed on the file when this PR is merged**
=> Removing `published: false` from Alix's post

.github/PULL_REQUEST_TEMPLATE.md, _data/members.yml
Technical change to JOB roles, removal of non-employed team members, adding PR template.
=> Updating members list

_posts/2016-06-10-Remotely-Entertaining.md
This blog is a follow on from the keynote session we ran on remote
working, please provide feedback and any other key points you think
would be useful.
=> Remotely Entertaining

_posts/2016-07-06-Remotely-Entertaining.md
=> Fix formatting.

_posts/2016-09-26-why-estimate.md
Fix the syntax for the headings in #119
=> Fix syntax for headings

_posts/2016-10-11-a-remote-month.md
=> Changing title format

_data/members.yml
Bring the [http://tech.holidayextras.co.uk/team/](http://tech.holidayextras.co.uk/team/) page up to date.
=> Remove Joe & add Louis back

_posts/2016-10-21-remote-productivity.md
Remote: Productivity (improvements on name are welcome)
This blog is all about how working remotely has made me more productive and also how I've adapted my work style around working from home
=> Remote: Productivity - how working from home has hepled me

_posts/2016-11-04-remotely-healthy.md
Remote: The Healthy Choice
Third in the remote series, this post focuses on how remote working can enable you to live a healthier lifestyle. It explores the benefits of taking control of you diet, exercise and sleep, to help productivity.
=> Remote - leading a healthier lifestyle

_includes/footer.html
Adds a twitter button to the site footer. Simples.
=> Add twitter to footer

_posts/2017-27-01-pair-programming-with-your-kids.md
Pair programming with your kids. Any other suggestions are welcome
This sparked from a discussion in #twitter around Amazon's STEM toy subscription. Instead of tweeting out the link, I thought we could convert this into an opportunity to recommend some cool resources to help with teaching kids how to code.
I admit my grammar and spelling isn't the best, anything I have missed please shout
=> Pair programming with your kids

_data/members.yml
=> adding member

_data/members.yml
=> Adding Stef to the member database

README.md
I've had a first stab at updating the README to enable less technical people to be able to use the terminal and git in order to create and post their blog.
Please feel free to make suggestions.
=> Updates the blog README

_posts/2017-04-21-what-has-testing-taught-you.md
This fixes a problem with front matter formatting. The original article was reviewed and approved.
=> Revert "Revert "What has testing taught you?""

_layouts/team.html
Not all members want to put their twitter handle publicly, this makes it optional via the config
=> Makes having twitter optional

_posts/2017-08-30-new-kids-on-the-block.md
=> adding a space
